apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: freeze-daemon-crio
  namespace: knative-serving
spec:
  selector:
    matchLabels:
      name: freeze-daemon-crio
  template:
    metadata:
      labels:
        name: freeze-daemon-crio
    spec:
      serviceAccountName: freeze-tokenreview
      nodeSelector:
        knative.dev/container-runtime: crio
      containers:
        - name: daemon
          securityContext:
            runAsUser: 0
          image: ko://knative.dev/container-freezer/cmd/daemon
          env:
            - name: RUNTIME_TYPE
              value: "crio"
            - name: FREEZER_LOGGING_CONFIG
              valueFrom:
                configMapKeyRef:
                  name: config-freezer
                  key: freezer-logging-config
            - name: FREEZER_LOGGING_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: config-freezer
                  key: freezer-logging-level
          ports:
            - containerPort: 8080
              hostPort: 9696
          volumeMounts:
            - name: crio-socket
              mountPath: /var/run/crio/crio.sock
      volumes:
        - name: crio-socket
          hostPath:
            path: /var/run/crio/crio.sock
            type: Socket
