name: Kubeadm e2e tests

on:
  pull_request:
    branches: [ 'main' ]

  push:
    branches: [ 'main' ]

defaults:
  run:
    shell: bash
    working-directory: ./src/knative.dev/container-freezer

jobs:
  e2e-tests:
    name: containerd-based e2e tests
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go 1.17.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x

      - name: Install Dependencies
        working-directory: ./
        run: |
          echo '::group:: install ko'
          curl -L https://github.com/google/ko/releases/download/v0.9.3/ko_0.9.3_Linux_x86_64.tar.gz | tar xzf - ko
          chmod +x ./ko
          sudo mv ko /usr/local/bin
          echo '::endgroup::'
      - name: Check out code onto GOPATH
        uses: actions/checkout@v2
        with:
          path: ./src/knative.dev/container-freezer
      - name: Run e2e Tests
        run: |
          ./test/e2e-kubeadm.sh